//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopCheck.Library.Tests.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestObject", Namespace="http://schemas.datacontract.org/2004/07/PromcodeServiceLibrary.Classes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoopCheck.Library.Tests.ServiceReference1.GetPromocodeRequest))]
    public partial class RequestObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientData9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CultureCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CoopCheck.Library.Tests.ServiceReference1.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssuanceProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromocodeProgramIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData1 {
            get {
                return this.ClientData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData1Field, value) != true)) {
                    this.ClientData1Field = value;
                    this.RaisePropertyChanged("ClientData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData10 {
            get {
                return this.ClientData10Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData10Field, value) != true)) {
                    this.ClientData10Field = value;
                    this.RaisePropertyChanged("ClientData10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData2 {
            get {
                return this.ClientData2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData2Field, value) != true)) {
                    this.ClientData2Field = value;
                    this.RaisePropertyChanged("ClientData2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData3 {
            get {
                return this.ClientData3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData3Field, value) != true)) {
                    this.ClientData3Field = value;
                    this.RaisePropertyChanged("ClientData3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData4 {
            get {
                return this.ClientData4Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData4Field, value) != true)) {
                    this.ClientData4Field = value;
                    this.RaisePropertyChanged("ClientData4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData5 {
            get {
                return this.ClientData5Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData5Field, value) != true)) {
                    this.ClientData5Field = value;
                    this.RaisePropertyChanged("ClientData5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData6 {
            get {
                return this.ClientData6Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData6Field, value) != true)) {
                    this.ClientData6Field = value;
                    this.RaisePropertyChanged("ClientData6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData7 {
            get {
                return this.ClientData7Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData7Field, value) != true)) {
                    this.ClientData7Field = value;
                    this.RaisePropertyChanged("ClientData7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData8 {
            get {
                return this.ClientData8Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData8Field, value) != true)) {
                    this.ClientData8Field = value;
                    this.RaisePropertyChanged("ClientData8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientData9 {
            get {
                return this.ClientData9Field;
            }
            set {
                if ((object.ReferenceEquals(this.ClientData9Field, value) != true)) {
                    this.ClientData9Field = value;
                    this.RaisePropertyChanged("ClientData9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CultureCode {
            get {
                return this.CultureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CultureCodeField, value) != true)) {
                    this.CultureCodeField = value;
                    this.RaisePropertyChanged("CultureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoopCheck.Library.Tests.ServiceReference1.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndClientId {
            get {
                return this.EndClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EndClientIdField, value) != true)) {
                    this.EndClientIdField = value;
                    this.RaisePropertyChanged("EndClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuanceProductId {
            get {
                return this.IssuanceProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuanceProductIdField, value) != true)) {
                    this.IssuanceProductIdField = value;
                    this.RaisePropertyChanged("IssuanceProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationIdField, value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainUserName {
            get {
                return this.MainUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MainUserNameField, value) != true)) {
                    this.MainUserNameField = value;
                    this.RaisePropertyChanged("MainUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromocodeProgramId {
            get {
                return this.PromocodeProgramIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PromocodeProgramIdField, value) != true)) {
                    this.PromocodeProgramIdField = value;
                    this.RaisePropertyChanged("PromocodeProgramId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/PromcodeServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdatePromocodeRequest", Namespace="http://schemas.datacontract.org/2004/07/PromcodeServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class UpdatePromocodeRequest : CoopCheck.Library.Tests.ServiceReference1.RequestObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierMessage1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierMessage2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierMessage3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewStatusCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewStatusReasonCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParticipantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromocodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedemptionMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierMessage1 {
            get {
                return this.CarrierMessage1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierMessage1Field, value) != true)) {
                    this.CarrierMessage1Field = value;
                    this.RaisePropertyChanged("CarrierMessage1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierMessage2 {
            get {
                return this.CarrierMessage2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierMessage2Field, value) != true)) {
                    this.CarrierMessage2Field = value;
                    this.RaisePropertyChanged("CarrierMessage2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierMessage3 {
            get {
                return this.CarrierMessage3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierMessage3Field, value) != true)) {
                    this.CarrierMessage3Field = value;
                    this.RaisePropertyChanged("CarrierMessage3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewStatus {
            get {
                return this.NewStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.NewStatusField, value) != true)) {
                    this.NewStatusField = value;
                    this.RaisePropertyChanged("NewStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewStatusComment {
            get {
                return this.NewStatusCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.NewStatusCommentField, value) != true)) {
                    this.NewStatusCommentField = value;
                    this.RaisePropertyChanged("NewStatusComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewStatusReasonCode {
            get {
                return this.NewStatusReasonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NewStatusReasonCodeField, value) != true)) {
                    this.NewStatusReasonCodeField = value;
                    this.RaisePropertyChanged("NewStatusReasonCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipantId {
            get {
                return this.ParticipantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipantIdField, value) != true)) {
                    this.ParticipantIdField = value;
                    this.RaisePropertyChanged("ParticipantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Promocode {
            get {
                return this.PromocodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PromocodeField, value) != true)) {
                    this.PromocodeField = value;
                    this.RaisePropertyChanged("Promocode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedemptionMessage {
            get {
                return this.RedemptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.RedemptionMessageField, value) != true)) {
                    this.RedemptionMessageField = value;
                    this.RaisePropertyChanged("RedemptionMessage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IssuePromocodeRequest", Namespace="http://schemas.datacontract.org/2004/07/PromcodeServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class IssuePromocodeRequest : CoopCheck.Library.Tests.ServiceReference1.RequestObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierMessage1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierMessage2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierMessage3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParticipantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromocodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedemptionMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierMessage1 {
            get {
                return this.CarrierMessage1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierMessage1Field, value) != true)) {
                    this.CarrierMessage1Field = value;
                    this.RaisePropertyChanged("CarrierMessage1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierMessage2 {
            get {
                return this.CarrierMessage2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierMessage2Field, value) != true)) {
                    this.CarrierMessage2Field = value;
                    this.RaisePropertyChanged("CarrierMessage2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierMessage3 {
            get {
                return this.CarrierMessage3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierMessage3Field, value) != true)) {
                    this.CarrierMessage3Field = value;
                    this.RaisePropertyChanged("CarrierMessage3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionTemplate {
            get {
                return this.DistributionTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionTemplateField, value) != true)) {
                    this.DistributionTemplateField = value;
                    this.RaisePropertyChanged("DistributionTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailMessage {
            get {
                return this.EmailMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailMessageField, value) != true)) {
                    this.EmailMessageField = value;
                    this.RaisePropertyChanged("EmailMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipantId {
            get {
                return this.ParticipantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipantIdField, value) != true)) {
                    this.ParticipantIdField = value;
                    this.RaisePropertyChanged("ParticipantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentReferenceId {
            get {
                return this.PaymentReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentReferenceIdField, value) != true)) {
                    this.PaymentReferenceIdField = value;
                    this.RaisePropertyChanged("PaymentReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Promocode {
            get {
                return this.PromocodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PromocodeField, value) != true)) {
                    this.PromocodeField = value;
                    this.RaisePropertyChanged("Promocode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedemptionMessage {
            get {
                return this.RedemptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.RedemptionMessageField, value) != true)) {
                    this.RedemptionMessageField = value;
                    this.RaisePropertyChanged("RedemptionMessage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPromocodeRequest", Namespace="http://schemas.datacontract.org/2004/07/PromcodeServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class GetPromocodeRequest : CoopCheck.Library.Tests.ServiceReference1.RequestObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierMessage1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierMessage2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierMessage3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributionTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParticipantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedemptionMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierMessage1 {
            get {
                return this.CarrierMessage1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierMessage1Field, value) != true)) {
                    this.CarrierMessage1Field = value;
                    this.RaisePropertyChanged("CarrierMessage1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierMessage2 {
            get {
                return this.CarrierMessage2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierMessage2Field, value) != true)) {
                    this.CarrierMessage2Field = value;
                    this.RaisePropertyChanged("CarrierMessage2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierMessage3 {
            get {
                return this.CarrierMessage3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierMessage3Field, value) != true)) {
                    this.CarrierMessage3Field = value;
                    this.RaisePropertyChanged("CarrierMessage3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributionTemplate {
            get {
                return this.DistributionTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributionTemplateField, value) != true)) {
                    this.DistributionTemplateField = value;
                    this.RaisePropertyChanged("DistributionTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailMessage {
            get {
                return this.EmailMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailMessageField, value) != true)) {
                    this.EmailMessageField = value;
                    this.RaisePropertyChanged("EmailMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipantId {
            get {
                return this.ParticipantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipantIdField, value) != true)) {
                    this.ParticipantIdField = value;
                    this.RaisePropertyChanged("ParticipantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentReferenceId {
            get {
                return this.PaymentReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentReferenceIdField, value) != true)) {
                    this.PaymentReferenceIdField = value;
                    this.RaisePropertyChanged("PaymentReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedemptionMessage {
            get {
                return this.RedemptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.RedemptionMessageField, value) != true)) {
                    this.RedemptionMessageField = value;
                    this.RaisePropertyChanged("RedemptionMessage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseObject", Namespace="http://schemas.datacontract.org/2004/07/PromcodeServiceLibrary.Classes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoopCheck.Library.Tests.ServiceReference1.GetPromocodeResponse))]
    public partial class ResponseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromocodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedemptionLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedemptionSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SwiftErrorReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Promocode {
            get {
                return this.PromocodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PromocodeField, value) != true)) {
                    this.PromocodeField = value;
                    this.RaisePropertyChanged("Promocode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedemptionLink {
            get {
                return this.RedemptionLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.RedemptionLinkField, value) != true)) {
                    this.RedemptionLinkField = value;
                    this.RaisePropertyChanged("RedemptionLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedemptionSite {
            get {
                return this.RedemptionSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.RedemptionSiteField, value) != true)) {
                    this.RedemptionSiteField = value;
                    this.RaisePropertyChanged("RedemptionSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SwiftErrorReason {
            get {
                return this.SwiftErrorReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.SwiftErrorReasonField, value) != true)) {
                    this.SwiftErrorReasonField = value;
                    this.RaisePropertyChanged("SwiftErrorReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdatePromocodeResponse", Namespace="http://schemas.datacontract.org/2004/07/PromcodeServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class UpdatePromocodeResponse : CoopCheck.Library.Tests.ServiceReference1.ResponseObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromocodeStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromocodeStatus {
            get {
                return this.PromocodeStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PromocodeStatusField, value) != true)) {
                    this.PromocodeStatusField = value;
                    this.RaisePropertyChanged("PromocodeStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IssuePromocodeResponse", Namespace="http://schemas.datacontract.org/2004/07/PromcodeServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class IssuePromocodeResponse : CoopCheck.Library.Tests.ServiceReference1.ResponseObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPromocodeResponse", Namespace="http://schemas.datacontract.org/2004/07/PromcodeServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class GetPromocodeResponse : CoopCheck.Library.Tests.ServiceReference1.ResponseObject {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PCService_Def")]
    public interface PCService_Def {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PCService_Def/GetPromocode", ReplyAction="http://tempuri.org/PCService_Def/GetPromocodeResponse")]
        CoopCheck.Library.Tests.ServiceReference1.GetPromocodeResponse GetPromocode(CoopCheck.Library.Tests.ServiceReference1.GetPromocodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PCService_Def/GetPromocode", ReplyAction="http://tempuri.org/PCService_Def/GetPromocodeResponse")]
        System.Threading.Tasks.Task<CoopCheck.Library.Tests.ServiceReference1.GetPromocodeResponse> GetPromocodeAsync(CoopCheck.Library.Tests.ServiceReference1.GetPromocodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PCService_Def/UpdatePromocode", ReplyAction="http://tempuri.org/PCService_Def/UpdatePromocodeResponse")]
        CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeResponse UpdatePromocode(CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PCService_Def/UpdatePromocode", ReplyAction="http://tempuri.org/PCService_Def/UpdatePromocodeResponse")]
        System.Threading.Tasks.Task<CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeResponse> UpdatePromocodeAsync(CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PCService_Def/IssuePromocode", ReplyAction="http://tempuri.org/PCService_Def/IssuePromocodeResponse")]
        CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeResponse IssuePromocode(CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PCService_Def/IssuePromocode", ReplyAction="http://tempuri.org/PCService_Def/IssuePromocodeResponse")]
        System.Threading.Tasks.Task<CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeResponse> IssuePromocodeAsync(CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PCService_DefChannel : CoopCheck.Library.Tests.ServiceReference1.PCService_Def, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PCService_DefClient : System.ServiceModel.ClientBase<CoopCheck.Library.Tests.ServiceReference1.PCService_Def>, CoopCheck.Library.Tests.ServiceReference1.PCService_Def {
        
        public PCService_DefClient() {
        }
        
        public PCService_DefClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PCService_DefClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PCService_DefClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PCService_DefClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CoopCheck.Library.Tests.ServiceReference1.GetPromocodeResponse GetPromocode(CoopCheck.Library.Tests.ServiceReference1.GetPromocodeRequest request) {
            return base.Channel.GetPromocode(request);
        }
        
        public System.Threading.Tasks.Task<CoopCheck.Library.Tests.ServiceReference1.GetPromocodeResponse> GetPromocodeAsync(CoopCheck.Library.Tests.ServiceReference1.GetPromocodeRequest request) {
            return base.Channel.GetPromocodeAsync(request);
        }
        
        public CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeResponse UpdatePromocode(CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeRequest request) {
            return base.Channel.UpdatePromocode(request);
        }
        
        public System.Threading.Tasks.Task<CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeResponse> UpdatePromocodeAsync(CoopCheck.Library.Tests.ServiceReference1.UpdatePromocodeRequest request) {
            return base.Channel.UpdatePromocodeAsync(request);
        }
        
        public CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeResponse IssuePromocode(CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeRequest request) {
            return base.Channel.IssuePromocode(request);
        }
        
        public System.Threading.Tasks.Task<CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeResponse> IssuePromocodeAsync(CoopCheck.Library.Tests.ServiceReference1.IssuePromocodeRequest request) {
            return base.Channel.IssuePromocodeAsync(request);
        }
    }
}
