//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopCheck.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoopCheckEntities : DbContext
    {
        public CoopCheckEntities()
            : base("name=CoopCheckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch> batches { get; set; }
        public virtual DbSet<check_tran> check_trans { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
        public virtual DbSet<vwCheck> vwChecks { get; set; }
        public virtual DbSet<vwPositivePay> vwPositivePay1 { get; set; }
        public virtual DbSet<vwVoidedPayment> vwVoidedPayments { get; set; }
        public virtual DbSet<vwPayment> vwPayments1 { get; set; }
        public virtual DbSet<bank_account> bank_accounts { get; set; }
        public virtual DbSet<vwUnclearedBatch> vwUnclearedBatches { get; set; }
        public virtual DbSet<CoopCheckClient> CoopCheckClients { get; set; }
        public virtual DbSet<CoopCheckJobLog> CoopCheckJobLogs { get; set; }
        public virtual DbSet<vwClientJobBatch> vwClientJobBatches { get; set; }
        public virtual DbSet<vwJobRpt> vwJobRpts { get; set; }
        public virtual DbSet<JobLog> JobLogs { get; set; }
        public virtual DbSet<vwBatchRpt> vwBatchRpts { get; set; }
        public virtual DbSet<vwOpenBatch> vwOpenBatches { get; set; }
    
        public virtual ObjectResult<vwJobRpt> GetJobPaymentsReport(Nullable<int> account_id, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vwJobRpt>("GetJobPaymentsReport", account_idParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<vwJobRpt> GetJobPaymentsReport(Nullable<int> account_id, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date, MergeOption mergeOption)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vwJobRpt>("GetJobPaymentsReport", mergeOption, account_idParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<vwBatchRpt> GetBatchPaymentReport(Nullable<int> account_id, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vwBatchRpt>("GetBatchPaymentReport", account_idParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<vwBatchRpt> GetBatchPaymentReport(Nullable<int> account_id, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date, MergeOption mergeOption)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vwBatchRpt>("GetBatchPaymentReport", mergeOption, account_idParameter, start_dateParameter, end_dateParameter);
        }
    }
}
