//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CoopCheck.Repository.Contracts.Interfaces;

namespace CoopCheck.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoopCheckEntities : DbContext, ICoopCheckEntities
    {
        public CoopCheckEntities()
            : base("name=CoopCheckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<Ibatch> batches { get; set; }
        public virtual IDbSet<Icheck_tran> check_trans { get; set; }
        public virtual IDbSet<Ivoucher> vouchers { get; set; }
        public virtual IDbSet<IvwCheck> vwChecks { get; set; }
        public virtual IDbSet<IvwPositivePay> vwPositivePays { get; set; }
        public virtual IDbSet<IvwVoidedPayment> vwVoidedPayments { get; set; }
        public IDbSet<IvwPayment> vwPayments { get; set; }
        public virtual IDbSet<Ibank_account> bank_accounts { get; set; }
        public virtual IDbSet<IvwUnclearedBatch> vwUnclearedBatches { get; set; }
        public virtual IDbSet<ICoopCheckClient> CoopCheckClients { get; set; }
        public virtual IDbSet<ICoopCheckJobLog> CoopCheckJobLogs { get; set; }
        public virtual IDbSet<IvwClientJobBatch> vwClientJobBatches { get; set; }
        public virtual IDbSet<IvwJobRpt> vwJobRpts { get; set; }
        public virtual IDbSet<IJobLog> JobLogs { get; set; }
        public virtual IDbSet<IvwBatchRpt> vwBatchRpts { get; set; }
        public virtual IDbSet<IvwOpenBatch> vwOpenBatches { get; set; }
    
        public virtual ObjectResult<IvwJobRpt> GetJobPaymentsReport(Nullable<int> account_id, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IvwJobRpt>("GetJobPaymentsReport", account_idParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<IvwJobRpt> GetJobPaymentsReport(Nullable<int> account_id, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date, MergeOption mergeOption)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IvwJobRpt>("GetJobPaymentsReport", mergeOption, account_idParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<IvwBatchRpt> GetBatchPaymentReport(Nullable<int> account_id, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IvwBatchRpt>("GetBatchPaymentReport", account_idParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<IvwBatchRpt> GetBatchPaymentReport(Nullable<int> account_id, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date, MergeOption mergeOption)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IvwBatchRpt>("GetBatchPaymentReport", mergeOption, account_idParameter, start_dateParameter, end_dateParameter);
        }
    }
}
