//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.Core.Objects;

namespace CoopCheck.Repository
{
    using System.Data.Entity;
    
    
    public interface ICoopCheckEntities
    {
        IDbSet<batch> batches { get; set; }
        IDbSet<check_tran> check_trans { get; set; }
        IDbSet<voucher> vouchers { get; set; }
        IDbSet<vwCheck> vwChecks { get; set; }
        IDbSet<vwPositivePay> vwPositivePays { get; set; }
        IDbSet<vwVoidedPayment> vwVoidedPayments { get; set; }
        IDbSet<vwPayment> vwPayments { get; set; }
        IDbSet<bank_account> bank_accounts { get; set; }
        IDbSet<vwUnclearedBatch> vwUnclearedBatches { get; set; }
        IDbSet<CoopCheckClient> CoopCheckClients { get; set; }
        IDbSet<CoopCheckJobLog> CoopCheckJobLogs { get; set; }
        IDbSet<vwClientJobBatch> vwClientJobBatches { get; set; }
        IDbSet<vwJobRpt> vwJobRpts { get; set; }
        IDbSet<JobLog> JobLogs { get; set; }
        IDbSet<vwBatchRpt> vwBatchRpts { get; set; }
        IDbSet<vwOpenBatch> vwOpenBatches { get; set; }

        ObjectResult<vwJobRpt> GetJobPaymentsReport(Nullable<int> account_id, Nullable<System.DateTime> start_date,
            Nullable<System.DateTime> end_date);

        ObjectResult<vwJobRpt> GetJobPaymentsReport(Nullable<int> account_id, Nullable<System.DateTime> start_date,
            Nullable<System.DateTime> end_date, MergeOption mergeOption);

        ObjectResult<vwBatchRpt> GetBatchPaymentReport(Nullable<int> account_id, Nullable<System.DateTime> start_date,
            Nullable<System.DateTime> end_date);


        ObjectResult<vwBatchRpt> GetBatchPaymentReport(Nullable<int> account_id, Nullable<System.DateTime> start_date,
            Nullable<System.DateTime> end_date, MergeOption mergeOption);

    }
}
