//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CoopCheck.Repository.Contracts.Interfaces;
using System.Runtime.Serialization;

namespace CoopCheck.Repository
{
    
    [DataContract]
    public partial class bank_account : Ibank_account
    {
    }
    
    [DataContract]
    public partial class batch : Ibatch
    {
    }
    
    [DataContract]
    public partial class check_tran : Icheck_tran
    {
    }
    
    [DataContract]
    public partial class CoopCheckClient : ICoopCheckClient
    {
    }
    
    [DataContract]
    public partial class CoopCheckJobLog : ICoopCheckJobLog
    {
    }
    
    [DataContract]
    public partial class JobLog : IJobLog
    {
    }
    
    [DataContract]
    public partial class voucher : Ivoucher
    {
    }
    
    [DataContract]
    public partial class vwBatchRpt : IvwBatchRpt
    {
    }
    
    [DataContract]
    public partial class vwCheck : IvwCheck
    {
    }
    
    [DataContract]
    public partial class vwClientJobBatch : IvwClientJobBatch
    {
    }
    
    [DataContract]
    public partial class vwJobRpt : IvwJobRpt
    {
    }
    
    [DataContract]
    public partial class vwOpenBatch : IvwOpenBatch
    {
    }
    
    [DataContract]
    public partial class vwPayment : IvwPayment
    {
    }
    
    [DataContract]
    public partial class vwPositivePay : IvwPositivePay
    {
    }
    
    [DataContract]
    public partial class vwUnclearedBatch : IvwUnclearedBatch
    {
    }
    
    [DataContract]
    public partial class vwVoidedPayment : IvwVoidedPayment
    {
    }
    
}
