//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopCheck.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    
    public interface IDbContextCoopCheckEntities
    {
        IDbSet<batch> batches { get; set; }
        IDbSet<check_tran> check_trans { get; set; }
        IDbSet<voucher> vouchers { get; set; }
        IDbSet<vwCheck> vwChecks { get; set; }
        IDbSet<vwPositivePay> vwPositivePay1 { get; set; }
        IDbSet<vwVoidedPayment> vwVoidedPayments { get; set; }
        IDbSet<vwPayment> vwPayments1 { get; set; }
        IDbSet<bank_account> bank_accounts { get; set; }
        IDbSet<vwUnclearedBatch> vwUnclearedBatches { get; set; }
        IDbSet<CoopCheckClient> CoopCheckClients { get; set; }
        IDbSet<CoopCheckJobLog> CoopCheckJobLogs { get; set; }
        IDbSet<vwClientJobBatch> vwClientJobBatches { get; set; }
        IDbSet<vwJobRpt> vwJobRpts { get; set; }
        IDbSet<JobLog> JobLogs { get; set; }
        IDbSet<vwBatchRpt> vwBatchRpts { get; set; }
        IDbSet<vwOpenBatch> vwOpenBatches { get; set; }
    }
}
