//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CoopCheck.Repository.Contracts.Interfaces;

namespace CoopCheck.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobLog : IJobLog
    {
        public int JobNum { get; set; }
        public string ClientID { get; set; }
        public string JobName { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public string priMethod { get; set; }
        public string scdMethod { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Ended { get; set; }
        public string ProjMgr { get; set; }
        public string scdPrjMgr { get; set; }
        public Nullable<float> ProdRate { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> Location { get; set; }
        public string Client_Job__ { get; set; }
        public string PO__ { get; set; }
        public string product { get; set; }
        public string ref_jobs { get; set; }
        public string invoice { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
