//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopCheck.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBatchRpt
    {
        public string account_name { get; set; }
        public Nullable<int> job_num { get; set; }
        public Nullable<System.DateTime> batch_date { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public Nullable<decimal> batch_amount { get; set; }
        public int batch_num { get; set; }
        public string payment_type { get; set; }
        public Nullable<int> total_cnt { get; set; }
        public Nullable<int> open_cnt { get; set; }
        public Nullable<int> cleared_cnt { get; set; }
        public Nullable<decimal> open_amount { get; set; }
        public Nullable<decimal> cleared_amount { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string first_check_num { get; set; }
        public string last_check_num { get; set; }
    }
}
