//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopCheck.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientJobBatch
    {
        public int batch_num { get; set; }
        public Nullable<decimal> batch_amount { get; set; }
        public Nullable<System.DateTime> batch_date { get; set; }
        public string batch_dscr { get; set; }
        public string marketing_research_message { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public Nullable<int> respondent_batch_id { get; set; }
        public string study_topic { get; set; }
        public string thank_you_1 { get; set; }
        public string thank_you_2 { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string usr { get; set; }
        public bool active { get; set; }
        public string client_job__ { get; set; }
        public string clientid { get; set; }
        public string clientname { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> ended { get; set; }
        public string invoice { get; set; }
        public Nullable<bool> ismaster { get; set; }
        public string jobname { get; set; }
        public int jobnum { get; set; }
        public Nullable<int> location { get; set; }
        public string po__ { get; set; }
        public string primethod { get; set; }
        public Nullable<float> prodrate { get; set; }
        public string product { get; set; }
        public string projmgr { get; set; }
        public string ref_jobs { get; set; }
        public string scdmethod { get; set; }
        public string scdprjmgr { get; set; }
        public Nullable<System.DateTime> started { get; set; }
        public Nullable<int> total { get; set; }
    }
}
