//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClean.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataCleanEntities : DbContext
    {
        public DataCleanEntities()
            : base("name=DataCleanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MelissaResultReference> MelissaResultReferences { get; set; }
        public virtual DbSet<DataCleanEventLog> DataCleanEventLogs { get; set; }
        public virtual DbSet<DataCleanStat> DataCleanStats { get; set; }
    }
}
