//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClean.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MelissaResultReference
    {
        public string Code { get; set; }
        public string Type { get; set; }
        public string LongDescription { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<bool> AlternateAddressExists { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
